### ISSUE TITLE
available() should use signed integer

### ISSUE THREAD

**Issue by WayneKeenan** [sparkfun/SparkFun_MAX3010x_Sensor_Library#12]
The `uint8_t` on the line below should be an `int8_t` otherwise the comparison after is never true and it has a side effect of the client processing bogus readings.

https://github.com/sparkfun/SparkFun_MAX3010x_Sensor_Library/blob/master/src/MAX30105.cpp#L528

**Comment by nseidle** [comment]
You are very right! Thank you.

**Comment by nseidle** [comment]
Will be fixed in the latest release.
