### ISSUE TITLE
Connecting two sensors to one Arduino

### ISSUE THREAD

**Issue by kyangEPS** [sparkfun/SparkFun_MAX3010x_Sensor_Library#23]
I have two [MAX30102](https://www.amazon.com/MakerFocus-Heart-Rate-MAX30102-Compatible-Arduino/dp/B07GGSM8SP/ref=sr_1_4?crid=38575Z7QZNSXY&keywords=arduino+heart+rate+sensor&qid=1572623467&sprefix=arduino+heart+rate%2Caps%2C260&sr=8-4) sensor modules. How can I program and connect them both to one Arduino? How can I communicate to two items on one I2C bus?

Thank you!

**Comment by nseidle** [comment]
The I2C address is locked to one address so to connect two you'll need a [Mux](https://www.sparkfun.com/products/14685).
