### ISSUE TITLE
I2C_SPEED_FAST was not declared in this scope

### ISSUE THREAD

**Issue by gracepakp** [sparkfun/SparkFun_MAX3010x_Sensor_Library#40]
Hello, i've been working on project with MAX30102 by MH-ET LIVE breakboard and ESP32. I already install the library for MAX30105 in Arduino IDE manage libraries but when i try Example8-SPO2 i got error that say I2C_SPEED_FAST was not declared in this scope. Is there anyone who could help me with this problem? Thank you.

**Comment by gracepakp** [comment]
i solved the problem. it's because arduino ide read other library instead of MAX30105.h

**Comment by SADAMALHAAG** [comment]
i have the same problem how did you solve it..
