### ISSUE TITLE
Example 7 variable type mis-match

### ISSUE THREAD

**Issue by biomurph** [sparkfun/SparkFun_MAX3010x_Sensor_Library#45]
This is a simple and quite unintelligent bug.
It's just hanging out there right in the middle of everything... so obvious... line 50

> byte sampleRate = 400; //Options: 50, 100, 200, 400, 800, 1000, 1600, 3200

But a byte only counts to 255 and then rolls over to 0.
So any sample rate over 200 would be... 

Gotta say, I was pulling my hair out with the o'scope on the bench and everything.
The `.setup()` receives an `int` in the sampleRate space. Easy fix.

**Comment by nseidle** [comment]
Thanks @biomurph! Fixed.

**Comment by biomurph** [comment]
smiley face
