### ISSUE TITLE
Why all the bit shifting

### ISSUE THREAD

**Issue by danieldeesousa** [sparkfun/SparkFun_MAX3010x_Sensor_Library#8]
Hi there,

I am using this algorithm and it has been working fine for me so far but I am trying to understand how it actually works.

On line 138 of the heartrate.cpp source file, what is the purpose of performing so many bit shifts, especially the bit shift to the right by 4.

I have some experience with FIR filters and basic DSP but am confused on the purpose of this.

Thanks,

DD

**Comment by nseidle** [comment]
heartrate.cpp is Maxim's library. It would be best to contact them for their logic.
