### ISSUE TITLE
Compilation Error on Wemos D1 Mini

### ISSUE THREAD

**Issue by AbirKuundu** [sparkfun/SparkFun_MAX3010x_Sensor_Library#9]
When I compile Example8_SPO2 on Arduino Nano, it compiles perfectly. When I try to change the board and compile it on Wemos D1 Mini or NodeMCU 1.0, it throws compilation error like below:

Arduino: 1.8.5 (Windows 10), Board: "WeMos D1 mini Pro, 80 MHz, 16M (15M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 921600"

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:89:1: error: expected identifier before '{' token

 {

 ^

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:89:1: error: expected ')' before '{' token

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp: In function 'void maxim_heart_rate_and_oxygen_saturation(uint32_t*, int32_t, uint32_t*, int32_t*, int8_t*, int)':

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:134:6: error: 'pn_heart_rate' was not declared in this scope

     *pn_heart_rate =(int32_t)( (FS*60)/ n_peak_interval_sum );

      ^

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:135:6: error: 'pch_hr_valid' was not declared in this scope

     *pch_hr_valid  = 1;

      ^

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:138:6: error: 'pn_heart_rate' was not declared in this scope

     *pn_heart_rate = -999; // unable to calculate because # of peaks are too small

      ^

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:139:6: error: 'pch_hr_valid' was not declared in this scope

     *pch_hr_valid  = 0;

      ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:89:1: error: expected identifier before '{' token

 {

 ^

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:89:1: error: expected ')' before '{' token

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp: In function 'void maxim_heart_rate_and_oxygen_saturation(uint32_t*, int32_t, uint32_t*, int32_t*, int8_t*, int)':

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:134:6: error: 'pn_heart_rate' was not declared in this scope

     *pn_heart_rate =(int32_t)( (FS*60)/ n_peak_interval_sum );

      ^

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:135:6: error: 'pch_hr_valid' was not declared in this scope

     *pch_hr_valid  = 1;

      ^

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:138:6: error: 'pn_heart_rate' was not declared in this scope

     *pn_heart_rate = -999; // unable to calculate because # of peaks are too small

      ^

C:\Users\abir.kundu\Documents\Arduino\libraries\SparkFun_MAX3010x_Pulse_and_Proximity_Sensor_Library\src\spo2_algorithm.cpp:139:6: error: 'pch_hr_valid' was not declared in this scope

     *pch_hr_valid  = 0;

      ^

exit status 1
Error compiling for board WeMos D1 mini Pro.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by SaulinPav** [comment]
Hello!
You should edit spo2_algorithm.cpp and uncomment line 70. You can check it here #10.
That worked for me.

**Comment by nseidle** [comment]
Saulin saves the day!

Abir, please give the new code a try. Please re-open if you continue to have problems.

**Comment by AbirKuundu** [comment]
The compilation error is fixed. Thanks a lot. I would try to run the code on my WeMos D1 Mini and let you know if I face any difficulty.

**Comment by AbirKuundu** [comment]
Program Example8_SPO2 compiled successfully and got uploaded to Wemos D1 Mini.
Board I'm using MAX30102. Wire connection is as follows:
WeMos D1 -> MAX30102
5V		Vin
G		Gnd
D1		SCL
D2		SDA
GND		IRD (Without this my IR Led does light up)
